name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number to publish (e.g., 1.0.0)
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    - name: Install and Build
      run: npm ci

    - name: Publish Release
      uses: octorelease/octorelease@master
      env:
        GIT_COMMITTER_NAME: GitHub Actions
        GIT_COMMITTER_EMAIL: actions@github.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.ZOWE_ACTIONS_NPM_TOKEN }}
      with:
        new-version: ${{ github.event.inputs.version }}
